_BASE_: "Base-AFCD.yaml"
SOLVER:
  BASE_LR: 0.04
  CHECKPOINT_PERIOD: 5000
  GAMMA: 0.1
  IMS_PER_BATCH: 16
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MAX_ITER: 125000      # 200 epoch * (10k images / 16 IMS_PER_BATCH)
  MOMENTUM: 0.9
  STEPS: [62500, 93750, 112500] # epochs 100, 150, 180 (45k images)
  WARMUP_FACTOR: 0.001  # or BASE_LR/WARMUP_ITERS(?)
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
