# _BASE_: "Base-AFCD.yaml"
DATASETS:
  TEST: 
  - cartoon_val
  TRAIN:
  - cartoon_train
MODEL:
  ANCHOR_GENERATOR:
    ANGLES:
    - - 0
    ASPECT_RATIOS:
    - - 1.0
    SIZES:
    - - 16
    - - 32
    - - 64
    - - 128
    - - 256
    - - 512
  BACKBONE:
    FREEZE_AT: 2
  ROI_BOX_HEAD:
    NUM_CLASSES: 1
  WEIGHTS: https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl
OUTPUT_DIR: ./output
SOLVER:
  BASE_LR: 0.04
  CHECKPOINT_PERIOD: 5000
  GAMMA: 0.1
  IMS_PER_BATCH: 16
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MAX_ITER: 562500      # 200 epoch * (45k images / 16 IMS_PER_BATCH)
  MOMENTUM: 0.9
  STEPS: [281250, 421875, 506250] # epochs 100, 150, 180 (45k images)
  WARMUP_FACTOR: 0.001  # or BASE_LR/WARMUP_ITERS(?)
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
TEST:
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 10000  
INPUT:
  MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536, 1792, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  FORMAT: BGR
DATALOADER:
  NUM_WORKERS: 2